package io.dbguardian.runtime;

public enum FailoverEventType {
    INITIALIZED,
    MASTER_CONFIRMED,
    SLAVE_PROMOTED,
    DEGRADED_ENTERED,
    REDIS_STATE_REPLAYED,
    RECOVERY_STARTED,
    RECOVERY_COMPLETED,
    REPLICATION_REBUILT,
    ORIGINAL_MASTER_RECOVERY_STARTED,
    ORIGINAL_MASTER_CATCHUP_STARTED,
    ORIGINAL_MASTER_CATCHUP_COMPLETED,
    ORIGINAL_MASTER_RESTORED,
    REPLICATION_RESTORE_STARTED,
    REPLICATION_RESTORE_COMPLETED,
    CONTAMINATION_DETECTED,
    CONTAMINATION_RECOVERY_STARTED,
    CONSISTENCY_VERIFIED
}
